{
 "title": "Anna stable dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Namespace: default - WordPress + DB containers\n"
   }
  },
  {
   "title": "Pods Running - app",
   "type": "stat",
   "description": "namespace=\"kube-system\"",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "Is Pod Running?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"default\", pod=~\"anna-wordpress-wordpress.*\", phase=\"Running\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"default\", pod=~\"anna-wordpress-mariadb-0\", phase=\"Running\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "container restarts (stability)",
   "type": "stat",
   "description": "Shows if pods are crashing/restarting",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\"anna-wordpress-wordpress.*\"}[1h])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\"anna-wordpress-mariadb-0\"}[1h])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per pod over the last 5 minutes (0.0-1.0)",
   "type": "gauge",
   "description": "CPU usage per pod over the last 5 minutes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"anna-wordpress.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=\"anna-wordpress-mariadb-0\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"anna-wordpress.*\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=\"default\", pod=\"anna-wordpress-mariadb-0\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}