apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anna-wordpress.fullname" . }}-wordpress
  labels:
    app: wordpress
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress # same as pod label = which pods to manage
  template: # the pod configuration (template)
    metadata:
      labels:
        app: wordpress # pod gets labels
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image }}"
          ports:
            - containerPort: {{ .Values.wordpress.servicePort }} # port open inside container
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.env.WORDPRESS_DB_HOST }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.env.WORDPRESS_DB_USER }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.wordpress.env.WORDPRESS_DB_PASSWORD }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.env.WORDPRESS_DB_NAME }}
          resources:
            {{ toYaml .Values.wordpress.resources | nindent 12 }}








